#ifndef __UIContainer__
#define __UIContainer__

/**
@file
Subclass of Container, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include

namespace osg
{
  template <typename T> class ref_ptr; 
}

class wxWindow;
class VolumeViewer;
class VolumeInfo;

/** Implementing Container */
class UIContainer : public Container
{
	protected:
		// Handlers for Container events.
		void OnIdle(wxIdleEvent& event );
		void OnMenu(wxCommandEvent& event );
	public:
		/** Constructor */
		UIContainer(wxWindow* parent );
	//// end generated class members
    
    void RefreshChildren();
    wxWindow* OpenWindow(int id);

    osg::ref_ptr<VolumeViewer> m_topView;
    osg::ref_ptr<VolumeInfo> m_fileToLoad;

    bool m_sceneDirty;
};

#endif // __UIContainer__
