#ifndef __UIColorTable__
#define __UIColorTable__

/**
@file
Subclass of ColorTable, which is generated by wxFormBuilder.
*/

#include <set>

#include "UI_Base.h"
#include "UIControlPointInterface.h"
#include "UIControlPoint.h"

namespace osg
{
  template <typename T> class ref_ptr; 
  class TransferFunction1D;
}

class VolumeViewer;

//// end generated include

/** Implementing ColorTable */
class UIColorTable : public ColorTable, UIControlPointInterface
{
	protected:
		// Handlers for ColorTable events.
    void OnIdle( wxIdleEvent& event );
		void OnComboBox( wxCommandEvent& event );
		void OnButton( wxCommandEvent& event );
    void OnSpinCtrl( wxSpinEvent& event );
    void OnLeftDown( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
    void OnRightDown( wxMouseEvent& event );
    void OnRightUp( wxMouseEvent& event );
    void OnMotion( wxMouseEvent& event );
	public:
		/** Constructor */
		UIColorTable( wxWindow* parent );
	//// end generated class members
    void Init();
    void RemoveControlPoint(UIControlPoint* point);
    void RefreshControlPoint(UIControlPoint* point);
    void Draw(wxWindow* win);

    osg::ref_ptr<VolumeViewer> m_topView;
    osg::ref_ptr<osg::TransferFunction1D> m_transfer;
    std::set<UIControlPoint*, DereferenceLess> m_points;

    wxImage m_histogram;
    bool m_dirty;
};

#endif // __UIColorTable__
