#ifndef __UIControlPoint__
#define __UIControlPoint__

/**
@file
Subclass of ControlPoint, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

class UIFrame;
class UIControlPointInterface;

struct DereferenceLess
{
  template <typename T>
  bool operator()(T p1, T p2) const
  {
    return *p1 < *p2;
  }
};

/** Implementing ControlPoint */
class UIControlPoint : public ControlPoint
{
protected:
  // Handlers for ControlPoint events.
  void OnLeftDown( wxMouseEvent& event );
  void OnLeftUp( wxMouseEvent& event );
  void OnMotion( wxMouseEvent& event );
  void OnRightUp( wxMouseEvent& event );
public:
  /** Constructor */
  UIControlPoint(wxWindow* parent, UIControlPointInterface* colorTable);
  
  //// end generated class members
  UIControlPointInterface* m_parent;

  //// end generated include
  bool operator< (const UIControlPoint& p);

  bool m_drag;
  int m_x, m_y;
};

#endif // __UIControlPoint__
