#ifndef __UIDepthBuffer__
#define __UIDepthBuffer__

/**
@file
Subclass of DepthBuffer, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include
namespace osg
{
  template <typename T> class ref_ptr; 
  class Image;
}

class VolumeViewer;

/** Implementing DepthBuffer */
class UIDepthBuffer : public DepthBuffer
{
	protected:
		// Handlers for DepthBuffer events.
		void OnIdle( wxIdleEvent& event );
		void OnPaint( wxPaintEvent& event );
		void OnUpdate( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		UIDepthBuffer( wxWindow* parent);
	//// end generated class members

    void Init();;
    void ReloadDepthImage();

    osg::ref_ptr<osg::Image> m_depthImage;
    osg::ref_ptr<VolumeViewer> m_topView;
    
    bool m_dirty;
};

#endif // __UIDepthBuffer__
