#ifndef __UIExtractor__
#define __UIExtractor__

/**
@file
Subclass of Extractor, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"
#include "UIControlPoint.h"
#include <set>
#include "UIControlPointInterface.h"
#include "RayCastTechnique.h"

//// end generated include

/** Implementing Extractor */
class UIExtractor : public Extractor, UIControlPointInterface
{
	protected:
		// Handlers for Extractor events.
		void OnIdle( wxIdleEvent& event );
		void OnPaint( wxPaintEvent& event );
		void OnFileChanged( wxFileDirPickerEvent& event );
		void OnComboBox( wxCommandEvent& event );
		void OnButtonClick( wxCommandEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnMotion( wxMouseEvent& event );
	public:
		/** Constructor */
		UIExtractor( wxWindow* parent );
	//// end generated class members
    void RemoveControlPoint(UIControlPoint* point);
    void RefreshControlPoint(UIControlPoint* point);
    void draw(wxWindow*);
	  void readInput();
    void genOcclusion();

    struct DereferenceLess
    {
      template <typename T>
      bool operator()(T p1, T p2) const
      {
        return *p1 < *p2;
      }
    };
    RayCastTechnique* m_technique;

    static bool m_dirty;
    bool m_swapBytes;
    std::set<UIControlPoint*, DereferenceLess> m_points;
	  wxImage m_hist;
    wxString m_inputVolume;
	  wxString m_outputVolume;
	  char path[_MAX_PATH];
    int m_voxelSize;
};

#endif // __UIExtractor__
