#ifndef __UIFrameOccGen__
#define __UIFrameOccGen__

/**
@file
Subclass of FrameOccGen, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include
#include "UI_Base.h"
#include "UIPolyPoint.h"
#include <vector>
#include "wx/image.h"
#include "RayCastTechnique.h"

/** Implementing FrameOccGen */
class UIFrameOccGen : public FrameOccGen
{
	protected:
		// Handlers for FrameOccGen events.
		void OnIdle( wxIdleEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnMotion( wxMouseEvent& event );
		void OnCheckBox( wxCommandEvent& event );
    void OnPaint( wxPaintEvent& event );
	public:
		/** Constructor */
		UIFrameOccGen( wxWindow* parent );
	  //// end generated class members
    void readInput();
    void draw(wxWindow* win);
    void RemoveControlPoint(UIPolyPoint* point);
    void RefreshControlPoint(UIPolyPoint* point);
    void setCrossplot(const char* file);

    std::vector<UIPolyPoint*> m_poly1;
    std::vector<UIPolyPoint*> m_poly2;
    std::vector<UIPolyPoint*> m_poly3;
    UIPolyPoint* m_selection;
    wxImage m_spectrum;
    RayCastTechnique* m_technique;
    bool m_redraw;
    bool m_swapBytes;
    bool m_drag1;
    bool m_drag2;
    bool m_drag3;
    int m_x, m_y;
};

#endif // __UIFrameOccGen__
