#ifndef __UIOcclusionGeneration__
#define __UIOcclusionGeneration__

/**
@file
Subclass of OcclusionGeneration, which is generated by wxFormBuilder.
*/
#include <set>

#include "UI_Base.h"
#include "UIControlPoint.h"
#include "UIControlPointInterface.h"

//// end generated include

namespace osg
{
  template <typename T> class ref_ptr; 
}
class VolumeViewer;

/** Implementing OcclusionGeneration */
class UIOcclusionGeneration : public OcclusionGeneration, UIControlPointInterface
{
	protected:
		// Handlers for OcclusionGeneration events.
    void OnIdle( wxIdleEvent& event );
    void OnLeftDown( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnMotion( wxMouseEvent& event );
		void OnButton( wxCommandEvent& event );
		void OnRadio( wxCommandEvent& event );
		void OnSpinCtrl( wxSpinEvent& event );
	public:
		/** Constructor */
		UIOcclusionGeneration( wxWindow* parent );
	//// end generated class members
    void Init();
    void Draw(wxWindow* win);
    void GenerateOcclusion();
    void RemoveControlPoint(UIControlPoint* point);
    void RefreshControlPoint(UIControlPoint* point);
    void WriteVisibilityMapping(const char* path);

    std::set<UIControlPoint*, DereferenceLess> m_points;
    osg::ref_ptr<VolumeViewer> m_topView;

    wxImage m_histogram;

    bool m_dirty;
    bool m_cancel;
};

#endif // __UIOcclusionGeneration__
