#ifndef __UIOcclusionSpectrum__
#define __UIOcclusionSpectrum__

/**
@file
Subclass of OcclusionSpectrum, which is generated by wxFormBuilder.
*/
#include <vector>

#include "UI_Base.h"
#include "VolumeViewer.h"

//// end generated include

namespace osg
{
  template <typename T> class ref_ptr; 
};

class UIPolyPoint;
class VolumeViewer;

/** Implementing OcclusionSpectrum */
class UIOcclusionSpectrum : public OcclusionSpectrum
{
	protected:
		// Handlers for OcclusionSpectrum events.
		void OnIdle( wxIdleEvent& event );
    void OnClose( wxCloseEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnMotion( wxMouseEvent& event );
		void OnCheckBox( wxCommandEvent& event );
		void OnButton( wxCommandEvent& event );
	public:
		/** Constructor */
		UIOcclusionSpectrum( wxWindow* parent );
	//// end generated class members
    void Init();
    void Draw(wxWindow* win);
    void RemoveControlPoint(UIPolyPoint* point);
    void RefreshControlPoint(UIPolyPoint* point);

    osg::ref_ptr<VolumeViewer> m_topView;

    std::vector<UIPolyPoint*> m_poly1;
    std::vector<UIPolyPoint*> m_poly2;
    std::vector<UIPolyPoint*> m_poly3;

    UIPolyPoint* m_selection;
    
    bool m_active1;
    bool m_active2;
    bool m_active3;

    bool m_drag1;
    bool m_drag2;
    bool m_drag3;

    bool m_dirty;

    int m_x, m_y;

    wxImage m_spectrum;
};

#endif // __UIOcclusionSpectrum__
