#ifndef __UIPolyPoint__
#define __UIPolyPoint__

/**
@file
Subclass of PolyPoint, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include
class UIOcclusionSpectrum;

/** Implementing PolyPoint */
class UIPolyPoint : public PolyPoint
{
protected:
  // Handlers for PolyPoint events.
  void OnLeftDown( wxMouseEvent& event );
  void OnLeftUp( wxMouseEvent& event );
  void OnMotion( wxMouseEvent& event );
  void OnRightUp( wxMouseEvent& event );
public:
  /** Constructor */
  UIPolyPoint( wxWindow* parent );
  UIPolyPoint( wxWindow* parent, wxStaticBitmap* spectrum );

  //// end generated class members
  UIOcclusionSpectrum* m_parent;
  wxStaticBitmap* m_bmpSpectrum;
  
  bool m_drag;
  
  int m_x, m_y;
  
  int m_id;
};

#endif // __UIPolyPoint__
