#ifndef __UIRaw__
#define __UIRaw__

/**
@file
Subclass of Importer, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include

/** Implementing Importer */
class UIRaw : public Importer
{
	protected:
		// Handlers for Importer events.
		void OnComboBox( wxCommandEvent& event );
		void OnSpinCtrl( wxSpinEvent& event );
    void OnSetFocus( wxFocusEvent& event );
    void OnCheckBox( wxCommandEvent& event );
		void OnButton( wxCommandEvent& event );
	public:
		/** Constructor */
		UIRaw( wxWindow* parent );

    void LoadRawFile();
    void SetFileName(const char* filename);
	//// end generated class members
	
};

#endif // __UIRaw__
