#ifndef __UISettings__
#define __UISettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include

namespace osg
{
  template <typename T> class ref_ptr; 
}

class VolumeViewer;

/** Implementing Settings */
class UISettings : public Settings
{
	protected:
		// Handlers for Settings events.
    void OnClose( wxCloseEvent& event );
    void OnIdle( wxIdleEvent& event );
    void OnPaint( wxPaintEvent& event );
    void OnUpdate( wxUpdateUIEvent& event );
		void OnComboBox( wxCommandEvent& event );
		void OnCheckBox( wxCommandEvent& event );
    void OnSetFocus( wxFocusEvent& event );
    void OnSpinCtrl( wxSpinEvent& event );
	public:
		/** Constructor */
		UISettings( wxWindow* parent );
	//// end generated class members
    void Init();
    osg::ref_ptr<VolumeViewer> m_topView;
};

#endif // __UISettings__
