#ifndef __UISegY__
#define __UISegY__

/**
@file
Subclass of SegY, which is generated by wxFormBuilder.
*/

#include "UI_Base.h"

//// end generated include

/** Implementing SegY */
class UISegY : public SegY
{
	protected:
		// Handlers for SegY events.
		void OnButton( wxCommandEvent& event );
	public:
		/** Constructor */
		UISegY( wxWindow* parent );
	//// end generated class members
    void SetFileName(const char* filename);
	
};

#endif // __UISegY__
